### ISSUE TITLE
Forum/discord role from faction 

### ISSUE THREAD

**Issue by 0xBERNDOG** [SpaceAgeMP/issues#13]
Suggestion: have a user's faction on discord be automatically assigned. Currently manual, would require some steam authentication and a bot

Also have the forum display faction info if an account is linked to steam

**Comment by KieranFYI** [comment]
I belive Forum/Server/Discord Sync was discussed and is planned already.

**Comment by 0xBERNDOG** [comment]
Implemented https://spaceage.mp/threads/changes-2021-01-13.6/
